/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Empresa;
import Model.Empleado;
import Model.Producto;
import Model.Transaccion;
import Model.NodoEmpleado;
import Model.NodoProducto;
import Model.NodoTransaccion;
import Controller.ListaDobleProducto;
import Controller.ListaDobleEmpleado;
import Controller.ColaTransaccion;
import static View.DatosEmpresa.listaEmpleados;
import Controller.PersistenciaDatos;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Inicio extends javax.swing.JFrame {
    private Empresa empresa;

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null);
        empresa = PersistenciaDatos.cargarEmpresa(); //Cargamos la empresa al iniciar 
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        logo1 = new javax.swing.JLabel();
        fondociudad = new javax.swing.JLabel();
        Descripçion = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        txtNombreEmpresa = new javax.swing.JTextField();
        consejos = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnEntrar = new javax.swing.JButton();
        circulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 255, 153));
        background.setForeground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Roboto Medium", 2, 42)); // NOI18N
        titulo.setText("MicroSimu");
        titulo.setToolTipText("");
        background.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 220, 50));

        logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagenes/vision.png"))); // NOI18N
        logo1.setText("jLabel3");
        background.add(logo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 140, 160));

        fondociudad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagenes/ciudad.jpg"))); // NOI18N
        fondociudad.setText("jLabel2");
        background.add(fondociudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, -50, 390, 790));

        Descripçion.setFont(new java.awt.Font("Roboto ExtraBold", 0, 24)); // NOI18N
        Descripçion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagenes/remove background fre.png"))); // NOI18N
        Descripçion.setText("Simulador de MicroEmpresas");
        background.add(Descripçion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 370, -1));

        labelNombre.setFont(new java.awt.Font("Roboto Condensed Black", 0, 24)); // NOI18N
        labelNombre.setText("Nombre:");
        background.add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        txtNombreEmpresa.setForeground(new java.awt.Color(204, 204, 204));
        txtNombreEmpresa.setText("Ingrese el nombre de su empresa");
        txtNombreEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreEmpresaMousePressed(evt);
            }
        });
        txtNombreEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreEmpresaActionPerformed(evt);
            }
        });
        background.add(txtNombreEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 300, 40));

        jTextArea1.setBackground(new java.awt.Color(255, 255, 102));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Consejos:\n---------------------------------------------------------------------\n1.  💡 Empieza con un nombre creativo para tu empresa. ¡Esto le \ndará identidad desde el inicio!\n\n2.  📊 Administra bien tus recursos desde el principio: no gastes\ntodo en publicidad.\n\n3.  👥 Conoce a tus clientes: piensa en qué tipo de producto o\nservicio vas a ofrecer.\n\n4.  📈 Invierte en mejorar la calidad de tu producto para ganar\nmás clientes. \n\n5.  🔁 Guarda tu progreso y analiza tus decisiones para mejorar\ncada vez.");
        consejos.setViewportView(jTextArea1);

        background.add(consejos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 380, 290));

        btnEntrar.setBackground(new java.awt.Color(255, 255, 102));
        btnEntrar.setFont(new java.awt.Font("Roboto SemiCondensed Black", 0, 18)); // NOI18N
        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        background.add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 100, 40));

        circulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagenes/remove background fre.png"))); // NOI18N
        circulo.setText("jLabel6");
        background.add(circulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 40, -1));

        jLabel1.setFont(new java.awt.Font("Roboto ExtraBold", 2, 18)); // NOI18N
        jLabel1.setText("Bienvenido/a");
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel2.setText("by: Joel Vasquez, Keiner España, Bilson Caballero y Andrés Blanco");
        background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreEmpresaActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        // TODO add your handling code here:
        String nombre = txtNombreEmpresa.getText().trim();
        if (!nombre.isEmpty()) {
            DatosEmpresa.nombreEmpresa = nombre;
            DatosEmpresa.setNombreEmpresa(txtNombreEmpresa.getText());

            Dashboard dashboard = new Dashboard(empresa);
            dashboard.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Por favor, ingrese el nombre de la empresa.");
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void txtNombreEmpresaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreEmpresaMousePressed
        // TODO add your handling code here:
        txtNombreEmpresa.setText("");
        txtNombreEmpresa.setForeground(Color.black);
    }//GEN-LAST:event_txtNombreEmpresaMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Descripçion;
    private javax.swing.JPanel background;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel circulo;
    private javax.swing.JScrollPane consejos;
    private javax.swing.JLabel fondociudad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel logo1;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txtNombreEmpresa;
    // End of variables declaration//GEN-END:variables
}
