/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Empresa;
import Model.Empleado;
import Model.Producto;
import Model.Transaccion;
import Model.NodoEmpleado;
import Model.NodoProducto;
import Model.NodoTransaccion;
import Controller.ListaDobleProducto;
import Controller.ListaDobleEmpleado;
import Controller.ColaTransaccion;
import Controller.PersistenciaDatos;
import static View.DatosEmpresa.listaEmpleados;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author User
 */
public class RegistrarTransaccion extends javax.swing.JFrame {
    
    private Transacciones gestionartransacciones;
    private Empresa empresa;
    

    /**
     * Creates new form RegistrarTransaccion
     */
    public RegistrarTransaccion(Empresa empresa,Transacciones gestionartransacciones) {
        initComponents();
        cargarCombos();
        this.setLocationRelativeTo(null);
        this.empresa = empresa;
        this.gestionartransacciones = gestionartransacciones;
    }
    
    private void cargarCombos() {
    cbProductoTransaccion.removeAllItems();
    cbEmpleadoTransaccion.removeAllItems();

    NodoProducto p = DatosEmpresa.listaProductos.getCabeza();
    while (p != null) {
        cbProductoTransaccion.addItem(p.getProducto().getNombre());
        p = p.getSiguiente();
    }

    NodoEmpleado e = DatosEmpresa.listaEmpleados.getCabeza();
    while (e != null) {
        cbEmpleadoTransaccion.addItem(e.getEmpleado().getNombre());
        e = e.getSiguiente();
    }
   }
    
    private void limpiarCampos() {
    txtCantidadTransaccion.setText("");
    cbTipoTransaccion.setSelectedIndex(0);
    cbProductoTransaccion.setSelectedIndex(0);
    cbEmpleadoTransaccion.setSelectedIndex(0);
  }

    



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbTipoTransaccion = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbProductoTransaccion = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cbEmpleadoTransaccion = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtCantidadTransaccion = new javax.swing.JTextField();
        btnRegistrarTransaccion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 2, 36)); // NOI18N
        jLabel1.setText("Registrar Transaccion");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("Tipo:");

        cbTipoTransaccion.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        cbTipoTransaccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccione--", "Compra", "Venta" }));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("Producto:");

        cbProductoTransaccion.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        cbProductoTransaccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccione--", "Compra", "Venta" }));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setText("Empleado:");

        cbEmpleadoTransaccion.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        cbEmpleadoTransaccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccione--", "Compra", "Venta" }));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setText("Cantidad:");

        btnRegistrarTransaccion.setBackground(new java.awt.Color(255, 255, 115));
        btnRegistrarTransaccion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegistrarTransaccion.setText("Registrar");
        btnRegistrarTransaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarTransaccionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbTipoTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidadTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbEmpleadoTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbProductoTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(btnRegistrarTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbTipoTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cbProductoTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbEmpleadoTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtCantidadTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnRegistrarTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarTransaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarTransaccionActionPerformed
        // TODO add your handling code here:
        double total1;
        
         try {
        String tipo = cbTipoTransaccion.getSelectedItem().toString();
        String nombreProducto = cbProductoTransaccion.getSelectedItem().toString();
        String nombreEmpleado = cbEmpleadoTransaccion.getSelectedItem().toString();
        int cantidad = Integer.parseInt(txtCantidadTransaccion.getText());

        // Buscar objeto Producto
        Producto producto = DatosEmpresa.listaProductos.buscarpornombre(nombreProducto);
        if (producto == null) {
            JOptionPane.showMessageDialog(this, "Producto no encontrado.");
            return;
        }

        // Validar stock si es venta
        if (tipo.equals("Venta") && producto.getStock() < cantidad) {
            JOptionPane.showMessageDialog(this, "No hay suficiente stock para esta venta.");
            return;
        }

        // Actualizar stock según tipo
        if (tipo.equals("Venta")) {
            producto.setStock(producto.getStock() - cantidad);
        } else {
            producto.setStock(producto.getStock() + cantidad);
        }

        // Buscar objeto Empleado
        Empleado empleado = DatosEmpresa.listaEmpleados.buscarpornombre(nombreEmpleado);
        if (empleado == null) {
            JOptionPane.showMessageDialog(this, "Empleado no encontrado.");
            return;
        }
        
        if(cbTipoTransaccion.getSelectedItem().toString().equalsIgnoreCase("compra"))
        {
            total1 = producto.getPreciocompra() * cantidad;
        }
        else
        {
            total1 = producto.getPrecioventa() * cantidad;
        }
        
        double total = total1;

        
        Transaccion nueva = new Transaccion(tipo, nombreProducto, cantidad, nombreEmpleado, total);

        DatosEmpresa.colaTransacciones.encolar(nueva);
        DatosEmpresa.guardarDatos();
        JOptionPane.showMessageDialog(this, "Transacción registrada correctamente.");
        new Transacciones(empresa).setVisible(true);
        this.dispose();

        
        
        limpiarCampos();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_btnRegistrarTransaccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Empresa empresaprueba = new Empresa("Prueba");
        Transacciones transaccionprueba = new Transacciones(empresaprueba);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarTransaccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarTransaccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarTransaccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarTransaccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarTransaccion(empresaprueba,transaccionprueba).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarTransaccion;
    private javax.swing.JComboBox<String> cbEmpleadoTransaccion;
    private javax.swing.JComboBox<String> cbProductoTransaccion;
    private javax.swing.JComboBox<String> cbTipoTransaccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCantidadTransaccion;
    // End of variables declaration//GEN-END:variables
}
